FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    graphviz \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_cpu.txt .

RUN pip install --upgrade pip
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv --extra-index-url https://pytorch-geometric.com/whl/cpu
RUN pip install -r requirements_cpu.txt

COPY . .

CMD ["python", "main.py"]
